---
engine:
  name: podman

provisioner:
  name: ansible
  extra_args:
    - --diff
  env:
    ANSIBLE_NOCOLOR: False

verifier:
  name: goss
  extra_args:
    - --format
    - tap

instances:
  - name: ubuntu-22.04
    image: ubuntu-systemd:22.04
    playbook: ubuntu/playbook.yml
  - name: ubuntu-22.04-build
    image: ubuntu-systemd:22.04
    arch: amd64
    playbook: ubuntu/playbook.yml
    testfile: goss-build.yaml
    tags:
      - build
  - name: rockylinux-9.1
    image: rockylinux-systemd:9.1
  - name: rockylinux-9.1-build
    image: rockylinux-systemd:9.1
    testfile: goss-build.yaml
    tags:
      - build
